### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by novalis** [janestreet/ppx_bench#3]
I can't find any documentation on how to actually run the benchmarks. Would it be possible to add something to the README?  Thanks!

**Comment by aalekseyev** [comment]
Yeah, this is confusing. Sorry.

I'm about to add this paragraph to the doc of `ppx_bench`:

> These benchmarks are intended to be run with the runner provided by the `core_bench` library,
> `Inline_benchmarks_public.Runner.main`.  See the documentation of `core_bench` for more details.

And this info to the doc of `core_bench`:

> To run the benchmarks when using `dune`, you need to define
> your own executable that calls `Inline_benchmarks_public.Runner.main`. 
> You need to make sure that the benchmarks are linked into this executable, usually 
> by adding `(link_flags -linkall)` to the executable stanza to make sure the
> library dependencies are not dropped by the compiler.

Is that the information you were looking for? (sorry it's a few months late).

**Comment by novalis** [comment]
Probably!  I no longer remember what I was trying to do with ppx_bench but next time I need it, I'll take a look!
